[package]
name = "spotify-data"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.2.1", features = ["sqlite", "postgres"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
